## Built-in Data Types

### Python has the following data types built-in by default, in these categories:
- Text Type: 	str
- Numeric Types: 	int, float, complex
- Sequence Types: 	list, tuple, range
- Mapping Type: 	dict
- Set Types: 	set, frozenset
- Boolean Type: 	bool
- Binary Types: 	bytes, bytearray, memoryview
- None Type: 	NoneType

### Examples

In [ ]:
x = "Hello World"
print(x)
print(type(x)) 

Hello World
<class 'str'>


In [ ]:
x = 20
print(x)
print(type(x)) 

20
<class 'int'>


In [ ]:
x = 20.5
print(x)
print(type(x)) 

20.5
<class 'float'>


In [ ]:
x = 1j
print(x)
print(type(x)) 

1j
<class 'complex'>


In [ ]:
x = ["apple", "banana", "cherry"]
print(x)
print(type(x)) 

['apple', 'banana', 'cherry']
<class 'list'>


In [ ]:
x = ("apple", "banana", "cherry")
print(x)
print(type(x)) 

('apple', 'banana', 'cherry')
<class 'tuple'>


In [ ]:
x = ("apple", "banana", "cherry")
print(x)
print(type(x)) 

('apple', 'banana', 'cherry')
<class 'tuple'>


In [ ]:
x = {"name" : "John", "age" : 36}
print(x)
print(type(x)) 

{'name': 'John', 'age': 36}
<class 'dict'>


In [ ]:
x = {"apple", "banana", "cherry"}
print(x)
print(type(x)) 

{'banana', 'cherry', 'apple'}
<class 'set'>


In [ ]:
x = frozenset({"apple", "banana", "cherry"})
print(x)
print(type(x)) 

frozenset({'banana', 'cherry', 'apple'})
<class 'frozenset'>


In [ ]:
x = True
print(x)
print(type(x)) 

True
<class 'bool'>


In [ ]:
x = b"Hello"
print(x)
print(type(x)) 


b'Hello'
<class 'bytes'>


In [ ]:
x = bytearray(5)
print(x)
print(type(x)) 


bytearray(b'\x00\x00\x00\x00\x00')
<class 'bytearray'>


In [ ]:
x = memoryview(bytes(5))
print(x)
print(type(x)) 


<class 'memoryview'>


In [ ]:
x = None
print(x)
print(type(x)) 


None
<class 'NoneType'>


In [ ]:
print(print())


None


## Python Operators

### Python divides the operators in the following groups:

   - Arithmetic operators
   - Assignment operators
   - Comparison operators
   - Logical operators
   - Identity operators
   - Membership operators
   - Bitwise operators


In [ ]:
#Arithmetic Operators

x,y = 6,4

print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x%y)
print(x**y)
print(x//y)  #Floor division

10
2
24
1.5
2
1296
1


In [ ]:
#Assignment Operators

x=8

x+=3
print(x)

x-=3
print(x)

x*=3
print(x)

x/=3
print(x)

x%=3
print(x)

x=8
x//=3
print(x)

x**=3
print(x)

x=8

x &= 3
print(x)

x |= 3
print(x)

x ^= 3
print(x)

x >>= 3
print(x)

x <<= 3
print(x)

print(x := 3)

11
8
24
8.0
2.0
2
8
0
3
0
0
0
3


In [ ]:
# Comparison Operators

'''   
Operator 	Name 	        Example
==      	Equal 	                    x == y 	
!= 	        Not equal    	            x != y 	
> 	        Greater than             	x > y 	
< 	        Less than 	                x < y 	
>=        	Greater than or equal to 	x >= y 	
<=      	Less than or equal to      	x <= y
'''

'   \nOperator \tName \t        Example\n==      \tEqual \t                    x == y \t\n!= \t        Not equal    \t            x != y \t\n> \t        Greater than             \tx > y \t\n< \t        Less than \t                x < y \t\n>=        \tGreater than or equal to \tx >= y \t\n<=      \tLess than or equal to      \tx <= y\n'

In [ ]:
#Logical Operators
'''
Operator 	Description 	                                          Example 	
- and   	Returns True if both statements are true       	          x < 5 and  x < 10 	
- or 	    Returns True if one of the statements is true 	          x < 5 or x < 4 	
- not 	    Reverse the result, returns False if the result is true   not(x < 5 and x < 10)
'''

'\nOperator \tDescription \t                                          Example \t\n- and   \tReturns True if both statements are true       \t          x < 5 and  x < 10 \t\n- or \t    Returns True if one of the statements is true \t          x < 5 or x < 4 \t\n- not \t    Reverse the result, returns False if the result is true   not(x < 5 and x < 10)\n'

In [ ]:
#Identity Operators
'''
Operator 	Description 	                                            Example
is  	    Returns True if both variables are the same object 	        x is y 	
is not 	    Returns True if both variables are not the same object 	    x is not y

'''

'\nOperator \tDescription \t                                            Example\nis  \t    Returns True if both variables are the same object \t        x is y \t\nis not \t    Returns True if both variables are not the same object \t    x is not y\n\n'

In [ ]:
#Membership Operators

'''
Operator  	Description 	                                                                   Example 
in  	    Returns True if a sequence with the specified value is present in the object 	   x in y 	
not in    	Returns True if a sequence with the specified value is not present in the object   x not in y
'''

'\nOperator  \tDescription \t                                                                   Example \nin  \t    Returns True if a sequence with the specified value is present in the object \t   x in y \t\nnot in    \tReturns True if a sequence with the specified value is not present in the object   x not in y\n'

In [ ]:
#Bitwise Operators
'''
Operator     	Name 	                   Description 	                                                                                              Example 
&  	            AND 	                   Sets each bit to 1 if both bits are 1                                                                      x & y 	
| 	            OR 	                       Sets each bit to 1 if one of two bits is 1 	                                                              x | y 	
^ 	            XOR 	                   Sets each bit to 1 if only one of two bits is 1 	                                                          x ^ y 	
~ 	            NOT 	                   Inverts all the bits 	                                                                                  ~x 	
<<          	Zero fill left shift 	   Shift left by pushing zeros in from the right and let the leftmost bits fall off 	                      x << 2 	
>>          	Signed right shift 	       Shift right by pushing copies of the leftmost bit in from the left, and let the rightmost bits fall off 	  x >> 2
'''

'\nOperator     \tName \t                   Description \t                                                                                              Example \n&  \t            AND \t                   Sets each bit to 1 if both bits are 1                                                                      x & y \t\n| \t            OR \t                       Sets each bit to 1 if one of two bits is 1 \t                                                              x | y \t\n^ \t            XOR \t                   Sets each bit to 1 if only one of two bits is 1 \t                                                          x ^ y \t\n~ \t            NOT \t                   Inverts all the bits \t                                                                                  ~x \t\n<<          \tZero fill left shift \t   Shift left by pushing zeros in from the right and let the leftmost bits fall off \t                      x << 2 \t\n>>          \tSigned right shift \t       Shift ri

In [ ]:
a = True
print(not(a))

False


In [ ]:
mylist = ['apple', 'banana', 'cherry']
mylist[0] = 'kiwi'
print(mylist)

['kiwi', 'banana', 'cherry']


In [ ]:
mylist = ['apple', 'banana', 'cherry']
mylist[1:2] = ['kiwi', 'mango']
print(mylist)

['apple', 'kiwi', 'mango', 'cherry']


In [ ]:
import numpy as np

In [ ]:
arr=np.arange(0,5)

In [ ]:
arr

array([0, 1, 2, 3, 4])

In [ ]:
arr+arr

array([0, 2, 4, 6, 8])

In [ ]:
arr **arr

array([  1,   1,   4,  27, 256])

In [ ]:
np.linspace(1,100,20,retstep=True) #default 50 observations
#both the start and end are included in the array

(array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
         21.84210526,  27.05263158,  32.26315789,  37.47368421,
         42.68421053,  47.89473684,  53.10526316,  58.31578947,
         63.52631579,  68.73684211,  73.94736842,  79.15789474,
         84.36842105,  89.57894737,  94.78947368, 100.        ]),
 5.2105263157894735)

In [ ]:
np.linspace(1,100,retstep=True) #default 50 observations

(array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
          9.08163265,  11.10204082,  13.12244898,  15.14285714,
         17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
         25.24489796,  27.26530612,  29.28571429,  31.30612245,
         33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
         41.40816327,  43.42857143,  45.44897959,  47.46938776,
         49.48979592,  51.51020408,  53.53061224,  55.55102041,
         57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
         65.65306122,  67.67346939,  69.69387755,  71.71428571,
         73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
         81.81632653,  83.83673469,  85.85714286,  87.87755102,
         89.89795918,  91.91836735,  93.93877551,  95.95918367,
         97.97959184, 100.        ]),
 2.020408163265306)

In [ ]:
# Use or copy function

arr1=np.arange(0,20)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr2=arr1
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr1[1]=100

In [ ]:
arr1

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [ ]:
arr2 # So not recommended

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [ ]:
# Using Copy()
arr3=arr1.copy()

In [ ]:
arr3[10:]=100
arr3

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100])

In [ ]:
arr1

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

## Random Number generation
- numpy also has lots of ways to create random number arrays

In [ ]:
np.random.rand()

0.7268518201483285

In [ ]:
np.random.rand(10)*10

array([1.11247746, 7.3090478 , 5.49343046, 3.9364034 , 5.79655104,
       4.21825629, 9.03095964, 8.30640335, 6.12655469, 1.255584  ])

In [ ]:
#Creating arrayfrom uniform distribution

new_arr=np.random.rand(5,3,2)

In [ ]:
new_arr

array([[[0.17494124, 0.30387846],
        [0.50675115, 0.93273723],
        [0.54117051, 0.45864418]],

       [[0.73835278, 0.13299973],
        [0.69707483, 0.19422509],
        [0.78378473, 0.00228097]],

       [[0.43920494, 0.02347906],
        [0.2020669 , 0.34510355],
        [0.55573897, 0.64640498]],

       [[0.08759129, 0.56026028],
        [0.8077087 , 0.46138295],
        [0.45210473, 0.80590101]],

       [[0.92378613, 0.08174284],
        [0.20280406, 0.26097246],
        [0.54405395, 0.22030235]]])

## randn

In [ ]:
np.random.randn()

-1.0993315150430933

In [ ]:
arr1=np.random.randn(50)

In [ ]:
arr1

array([ 0.29138373,  1.13063556,  0.9771794 ,  0.1074879 ,  0.41392575,
        0.09626704,  0.29413274, -0.5234189 ,  1.50608872,  0.68607306,
        1.53125244, -2.51335323,  0.40387807,  0.08477941, -0.0861423 ,
        0.93586732, -0.09412395, -2.72077442, -0.96979705,  0.37791272,
        0.64681162,  0.65679412,  0.44923205, -0.52932831, -0.11382529,
        0.95868975,  0.42675728,  1.49969442, -1.38711645,  0.45707076,
       -0.75418021, -0.91704597,  1.82538656, -0.31149083,  0.99842619,
       -0.1231009 , -2.05232461, -0.18831461, -0.84559204, -1.32333992,
       -1.15014036, -0.05896041, -0.24093379, -0.06499387,  0.03882689,
       -0.98970847, -0.38734033, -0.53603894, -0.76437903,  0.30702012])

In [ ]:
arr1=np.random.randn(2,3)
arr1

array([[-0.10112222, -0.47053194, -0.61710319],
       [ 0.16070579, -0.35373655, -0.49367207]])

## randint 
- returns random integers from the low (inclusive) to high (exclusive)

In [ ]:
np.random.randint(10)

5

In [ ]:
np.random.randint(1,100)

52

In [ ]:
np.random.randint(1,100,20)

array([98, 98, 75, 15, 50, 57, 86, 79, 24,  9, 27, 73, 23, 13,  6, 53, 27,
       59, 93, 69])

## max,min,argmax,argmin
- these are useful methods for finding max or min values Or to find their index locations using argmin or argmax

In [ ]:
arr2=np.random.randint(1,100,20)
arr2

array([58, 74, 12, 62, 57, 36, 98, 70, 42, 68, 82, 83, 41, 70, 48,  7, 84,
       54, 80, 62])

In [ ]:
arr2.max()

98

In [ ]:
arr2.min()

7

In [ ]:
arr2.argmax() #index value

6

In [ ]:
arr2.argmin()  #index value

15

In [ ]:
arr=np.arange(10,100,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [ ]:
len(arr)

18

In [61]:
a="2356"
total=0

for i in a:
    total += int(i)
    
print(total)

16


In [63]:
a=2986
rev=0
while a>0:
    rev = rev*10 + a%10
    a = a//10
    
print(rev)

6892
