## Index


### Level-1: NumPy Arrays
- Basic Array Creation
- Array generation function
- Random generation function
- Array attributes
- Array Methods
- Reshaping and Resizing

### Level-2: Array Indexing and Slicing
- Indexing and Slicing of Vectors
- Indexing and Slicing of Matrix
- Boolean Indexing

### Level-3: Array Operations
- Arithmetic Operations
- Broadcasting
- Deep and Shallow Copy
- Matrix Operations
- Advance Array Manipulation
- Stacking Array
- Splitting Array

In [154]:
#import numpy library

import numpy as np

In [155]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [156]:
a = [1,2,3,"hello"]
a

[1, 2, 3, 'hello']

In [157]:
np.array(a)

array(['1', '2', '3', 'hello'], dtype='<U11')

In [158]:
a = [1,2,3,4.5]
a = np.array(a)
a

array([1. , 2. , 3. , 4.5])

In [159]:
oneD = [1,2,3,4]
twoD = [[1,2,3],[4,5,6],[7,8,9]]

print(np.array(oneD))
print('\n')
print(np.array(twoD))

[1 2 3 4]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [160]:
#Array generation function
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [161]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [162]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [163]:
#linspace = linear space

arr = np.linspace(1,5,3)   #having 2 evenly spaces
arr

array([1., 3., 5.])

In [164]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

### Random Generation Functions

In [165]:
np.random.rand(10)  #values between 0 and 1 (Normalization)

array([0.81248779, 0.74779017, 0.94333242, 0.63426998, 0.13940391,
       0.69724342, 0.24685167, 0.64385595, 0.29533532, 0.71525865])

In [166]:
np.random.randn(10)   #values betweem 3 and -3 (Standardization)

array([-0.00666412,  0.7756377 , -0.31211568,  0.24664089, -0.27457308,
        0.09406971,  0.49257971,  0.19852243, -0.820705  ,  0.41991751])

In [167]:
np.random.randint(8)

6

In [168]:
np.random.randint(10,20,10)

array([12, 13, 15, 14, 15, 10, 16, 11, 19, 10])

### Array Attributes

In [169]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,3]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [170]:
arr.shape  #Attributes dont need brackes() to call ,it gives error

(4, 3)

In [171]:
arr.size

12

In [172]:
arr.dtype

dtype('int32')

### Array Methods

In [173]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [174]:
arr.min()

1

In [175]:
arr.max()

9

In [176]:
arr.sum()

51

In [177]:
np.sum(arr,axis=0)  #Sum of each column elements

array([13, 17, 21])

In [178]:
np.sum(arr,axis=1)   #Sum of each row elements

array([ 6, 15, 24,  6])

In [179]:
arr.mean()

4.25

In [180]:
arr.std()

2.6180463454008347

In [181]:
arr.argmax()  #max value index

8

In [182]:
arr.argmin()  #min value index

0

### Reshaping and Resizing

In [183]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [184]:
arr.reshape(6,5)  #we should consider elements should be correctly fitted inside the new shaped array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [185]:
arr = arr.reshape(6,5) #changing the shape of previous array and storing in a varibale is called as resizing of an array

### NumPy Indexing and Slicing of Vectors

In [186]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [187]:
arr[8]

19

In [188]:
arr[1:6]

array([12, 13, 14, 15, 16])

In [189]:
arr[4:]

array([15, 16, 17, 18, 19, 20])

In [190]:
arr[::-2] #[start:end:steps]

array([20, 18, 16, 14, 12])

### NumPy Indexing and Slicing of Matrix

In [191]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [192]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [193]:
arr[1,2]

8

In [194]:
arr[4,3]

24

In [195]:
slice = arr[1:4,1:3]

In [196]:
slice

array([[ 7,  8],
       [12, 13],
       [17, 18]])

In [197]:
slice[0,1] = 88

In [198]:
slice

array([[ 7, 88],
       [12, 13],
       [17, 18]])

In [199]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7, 88,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [200]:
#to select one full column
arr_cl = arr[:,2:3]
arr_cl

array([[ 3],
       [88],
       [13],
       [18],
       [23],
       [28]])

In [201]:
arr_cl.reshape(1,6)

array([[ 3, 88, 13, 18, 23, 28]])

In [202]:
arr_cl = arr[:,2]
arr_cl

array([ 3, 88, 13, 18, 23, 28])

### Boolean Indexing

In [203]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [204]:
bool_index = arr % 2 ==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [205]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

### Arithmetic Operations

In [206]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

print(arr1, arr2)

[1 2 3 4 5] [ 6  7  8  9 10]


In [207]:
arr1 + arr2

array([ 7,  9, 11, 13, 15])

- Note: if u want to perform opertions on arrays the size/shape to should be similar

In [208]:
arr1 - arr2

array([-5, -5, -5, -5, -5])

In [209]:
arr1 ** arr2

array([      1,     128,    6561,  262144, 9765625])

In [210]:
arr1 / arr2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [211]:
arr1 // arr2

array([0, 0, 0, 0, 0])

In [212]:
#broadcasting
arr1+10

array([11, 12, 13, 14, 15])

In [213]:
arr = np.arange(1,60,2).reshape(6,5)
arr

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59]])

In [214]:
(arr + 10)//10

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6]], dtype=int32)

In [215]:
# deep and shallow copies

a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [216]:
slice_a = a[:8]
slice_a = slice_a*10
slice_a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [217]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

- Note: If same is done to list ,the original value are changes but we are doing on arrays

In [218]:
# deep copy
b = a
b[0] = 56

In [219]:
b

array([56,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [220]:
a

array([56,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [221]:
#shallow copy
a = np.arange(1,21)
b = a.copy()
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [222]:
b[0] = 56

In [223]:
b

array([56,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [224]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

### Matrix Operations

In [225]:
mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[5,6],[7,8]])

In [226]:
print(mat1)
print(mat2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [227]:
#Martix Muliplcation
mat1 @ mat2

array([[19, 22],
       [43, 50]])

In [228]:
np.dot(mat1,mat2)

array([[19, 22],
       [43, 50]])

In [229]:
#Transpose the matrix
mat1.T

array([[1, 3],
       [2, 4]])

In [230]:
#Stacking of arrays
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [231]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [232]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [233]:
#Column Stack
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### Splitting Array

In [234]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [235]:
np.hsplit(c,2)  #splitting horizontally in 2 halfs

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [236]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [237]:
np.vsplit(c,2)   #splitting vertically 2 halfs

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

### Exercises

In [238]:
#Valid Sudoku

s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

- To check if its true sudoku.
- Logic: The sum of each rows and columns should be 45 (sum from 1 to 9)
- As each row elements will be unique without repeating again and same goes for columns

In [239]:
s.sum()

405

In [240]:
b= np.sum(s,axis=1)
b == 45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [241]:
c = np.sum(s,axis=0)
c == 45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [242]:
for i in b:
    if i != 45:
        print("Sudoku is not valid")
        break
    else:
        print("Its valid for rows")

Its valid for rows
Its valid for rows
Its valid for rows
Its valid for rows
Its valid for rows
Its valid for rows
Its valid for rows
Its valid for rows
Its valid for rows


In [243]:
split1 = s[0:3,0:3]
split1

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [244]:
split2 = s[0:3,3:6]
split2

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [245]:
split3 = s[0:3,7:]
split2

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [246]:
#using for lLookupError
for i in range(0,9,3):
    for j in range(0,9,3):
        print(s[i:i+3,j:j+3])
        n = s[i:i+3,j:j+3]
        print("=",n.sum())

[[5 3 4]
 [6 7 2]
 [1 9 8]]
= 45
[[6 7 8]
 [1 9 5]
 [3 4 2]]
= 45
[[9 1 2]
 [3 4 8]
 [5 6 7]]
= 45
[[8 5 9]
 [4 2 6]
 [7 1 3]]
= 45
[[7 6 1]
 [8 5 3]
 [9 2 4]]
= 45
[[4 2 3]
 [7 9 1]
 [8 5 6]]
= 45
[[9 6 1]
 [2 8 7]
 [3 4 5]]
= 45
[[5 3 7]
 [4 1 9]
 [2 8 6]]
= 45
[[2 8 4]
 [6 3 5]
 [1 7 9]]
= 45


In [247]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [248]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [249]:
#Find the average age of students.
avg = np.mean(data[:,0])
avg

18.4

In [250]:
#Extract Math marks of all students.
print(data[:,1])

[85 92 76 65 90]


In [251]:
#Find the highest Science mark.
print(np.max(data[:,2]))

95


In [252]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1] > 90]

array([[19, 92, 88]])

In [253]:
#Increase Math marks of all students by 5.
data[:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [254]:
#Find how many students are younger than 19.
len(data[data[:,0]<19])

3

In [255]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:],axis=0)

array([86.6, 83.2])

In [256]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [257]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2] < 75] =0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])